### ISSUE TITLE
Crashes when I try to press "check now"

### ISSUE THREAD

**Issue by hiveliberty** [foogs/DamageWavePlugin#1]
```
16:36:23.3042 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'System.Collections.Generic.HashSet`1<VRage.Game.Entity.MyEntity> Sandbox.Game.Entities.MyEntities.GetEntities()'.
   at DamageWave.DamageWavePlugin.DamageProcess()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at RunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart()
   at Torch.VRageGame.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'System.Collections.Generic.HashSet`1<VRage.Game.Entity.MyEntity> Sandbox.Game.Entities.MyEntities.GetEntities()'.
   at DamageWave.DamageWavePlugin.DamageProcess()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at RunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart()
   at Torch.VRageGame.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by N1Ran** [comment]
I got one too
20:13:59.3723 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'System.Collections.Generic.HashSet`1<VRage.Game.Entity.MyEntity> Sandbox.Game.Entities.MyEntities.GetEntities()'.
   at DamageWave.DamageWavePlugin.DamageProcess()
   at DamageWave.DamageWavePlugin.Update() in C:\Users\Foogs\Documents\Visual Studio 2017\Projects\DamageWavePlugin\DamageWavePlugin.cs:line 84
   at Torch.Managers.PluginManager.UpdatePlugins()
   at Torch.Server.TorchServer.Update()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart()
   at Torch.VRageGame.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'System.Collections.Generic.HashSet`1<VRage.Game.Entity.MyEntity> Sandbox.Game.Entities.MyEntities.GetEntities()'.
   at DamageWave.DamageWavePlugin.DamageProcess()
   at DamageWave.DamageWavePlugin.Update() in C:\Users\Foogs\Documents\Visual Studio 2017\Projects\DamageWavePlugin\DamageWavePlugin.cs:line 84
   at Torch.Managers.PluginManager.UpdatePlugins()
   at Torch.Server.TorchServer.Update()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart()
   at Torch.VRageGame.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by foogs** [comment]
Fixed im think

**Comment by hiveliberty** [comment]
Yes, its working now) thx!
