### ISSUE TITLE
Pluging broken

### ISSUE THREAD

**Issue by hiveliberty** [foogs/DamageWavePlugin#2]
After some update plugin is broken and spam a ton of logs like this:
```20:18:56.2722 [INFO]   DamageWave: before start DamageWave 60
20:18:56.2722 [ERROR]  Torch.Managers.PluginManager: Plugin DamageWave threw an exception during update!
System.MissingMethodException: Method not found: 'Boolean Sandbox.Game.Entities.Cube.MySlimBlock.DoDamage(Single, VRage.Utils.MyStringHash, Boolean, System.Nullable`1<VRage.Game.ModAPI.MyHitInfo>, Int64)'.
   at DamageWave.DamageWavePlugin.DamageProcess()
   at DamageWave.DamageWavePlugin.Update()
   at Torch.Managers.PluginManager.UpdatePlugins() in C:\build\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 70```

**Comment by foogs** [comment]
@hiveliberty  i tested all works, test new rebuild : https://github.com/foogs/DamageWavePlugin/releases/tag/1.1.2.1

**Comment by hiveliberty** [comment]
@foogs yeah, thanks!) It's working now
